  <?php include '../views/sections/header.html'; ?>
  <?php include '../views/sections/logo_login.phtml'; ?>
  <?php include '../views/sections/menu.phtml'; ?>
  <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-3">
                <div id="filtros-produtos">
                    <div id="marcas"></div>
                    <div id="cores"></div>
                    <div id="valor"></div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-9">
                <div id="subcategoria-nome"></div>
                <div id="filtros-valor"></div>
                <div id="mostrar-produtos"></div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>
<script src="/assets/js/home.js"></script>