<?php
  include '../views/sections/header.html';
?>
<body class="d-flex align-items-center py-4 bg-body-tertiary">
<main class="form-signin w-100 container">
<a href="/" class="btn btn-primary">Loja</a><br>
  <?php if(isset($_GET['msg']) == 1) { ?>
    <br>
    <div class="text-success bg-success-subtle text-success-emphasis p-3"><b>Seu cadastro foi criado com sucesso!!! Faça login abaixo informando o seu email e senha!</b></div>
  <?php } ?>
  <br>
<form action="/login/validar" method="POST" novalidate>
  <h1 class="h3 mb-3 fw-normal">Faça Login</h1>
  <div class="form-floating">
    <input type="email" class="form-control" id="floatingInput" name="email" placeholder="name@example.com">
    <label for="floatingInput">e-mail</label>
  </div>
  <div class="form-floating">
    <input type="password" class="form-control" id="floatingPassword" name="senha" placeholder="Password">
    <label for="floatingPassword">senha</label>
  </div>
  <?php if(isset($_GET['erro']) == 2) { ?>
    <div class="bg-danger-subtle text-danger-emphasis p-3 mt-3">ATENÇÃO: e-mail ou senha inválidos!!! Por favor, informe o seu login e senha corretos!</div>
  <?php } ?>
  <div class="mt-3">
    <button class="btn btn-primary w-100 py-2" type="submit">Entrar</button>
  </div>
</form>
<hr>
<h3>Ainda não possui cadastro? Clique no botão abaixo e faça o seu cadastro!</h3>
<a href="/login/criar-login" class="btn btn-primary">Criar Cadastro</a>
</main>
  </body>
</html>
