<?php
    include '../views/sections/header.html';
?>
<body class="fundo-cinza">
    <div class="container">
        <div class="row">
            <div class="col-12 mt-3 mb-3">
                <a href="/cliente/painel" class="btn btn-primary">Voltar</a>
            </div>
        </div>
        <h1>Cadastrar Produto</h1>
        <div class="row">
            <div class="col-12">
                <form id="meuFormulario" enctype="multipart/form-data">
                    <label>Nome <sup>*</sup></label>
                    <input id="produto_nome" type="text" class="form-control mb-3" name="produto_nome">
                    <div id="produto_erro_nome"></div>
                    <label>Descrição:</label>
                    <textarea id="produto_descricao" type="text" class="form-control mb-3" name="produto_descricao" rows="5"></textarea>
                    <div id="produto_erro_descricao"></div>
                    <div class="row">
                        <div class="col-md-2 col-sm-6 col-6">
                                <label>Cor:</label>
                                <input id="produto_cor" type="text" class="form-control mb-3" name="produto_cor">
                        </div>
                        <div class="col-md-2 col-sm-6 col-6">
                            <label>Preço <sup>*</sup></label>
                            <input id="produto_valor_" type="text" class="form-control mb-3" name="produto_valor_">
                            <input id="produto_valor" type="text" class="form-control mb-3" name="produto_valor" hidden="true">
                            <div id="produto_erro_valor"></div>
                        </div>
                        <div class="col-12 col-md-8">
                            <div class="row">
                                <div class="col-4">
                                    <label>Nº parcelas:</label>
                                    <input id="produto_nro_parcelas" type="text" class="form-control mb-3" name="produto_nro_parcelas" onkeypress='return event.charCode >= 48 && event.charCode <= 57'>
                                    <div id="produto_erro_nro_parcelas"></div>
                                </div>
                                <div id="coluna-botao-calcular-parcelas" class="col-4">
                                    <button type="button" id="botao-calcular-parcelas" class="btn btn-primary mt-4">Calcular</button>
                                </div>
                                <div id="coluna-simbolo-igual" class="col-2">
                                    <h1 class="mt-3">=</h1>
                                </div>
                                <div class="col-2">
                                    <label>Valor Parcela:</label>
                                    <div id="valor_parcela"></div>
                                    <div id="valor_parcela_erro"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-3">
                            <label>Altura</label>
                            <input id="produto_altura" type="text" class="form-control mb-3" name="produto_altura" onkeyup="mascaraValorComVirgula('altura')">
                            <input id="produto_altura_valor" type="hidden" hidden="true" class="form-control mb-3" name="produto_altura_valor">
                            <div id="produto_erro_altura"></div>
                        </div>
                        <div class="col-3">
                            <label>Largura</label>
                            <input id="produto_largura" type="text" class="form-control mb-3" name="produto_largura" onkeyup="mascaraValorComVirgula('largura')">
                            <input id="produto_largura_valor" type="hidden" hidden="true" class="form-control mb-3" name="produto_largura_valor">
                            <div id="produto_erro_largura"></div>
                        </div>
                        <div class="col-3">
                            <label>Comprimento</label>
                            <input id="produto_comprimento" type="text" class="form-control mb-3" name="produto_comprimento" onkeyup="mascaraValorComVirgula('comprimento')">
                            <input id="produto_comprimento_valor" type="hidden" hidden="true" class="form-control mb-3" name="produto_comprimento_valor">
                            <div id="produto_erro_comprimento"></div>
                        </div>
                        <div class="col-3">
                            <label>Peso</label>
                            <input id="produto_peso" type="text" class="form-control mb-3" name="produto_peso" onkeyup="mascaraValorComVirgula('peso')">
                            <input id="produto_peso_valor" type="hidden" class="form-control mb-3" name="produto_peso_valor">
                            <div id="produto_erro_peso"></div>
                        </div> 
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-12">
                            <label>Incluir Imagem</label>
                            <input id="imagem" class="form-control mb-3" type="file" name="imagem" accept="image/jpg, image/jpeg, image/gif">
                            <div id="produto_erro_imagem"></div>
                            <hr>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <h5>Subcategorias Cadastradas <sup>*</sup></h5>
                            <div id="subcat-cadastradas"></div>
                            <div id="produto_erro_subcat"></div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <h5>Marcas Cadastradas <sup>*</sup></h5>
                            <div id="marcas-cadastradas"></div>
                            <div id="produto_erro_marca_selecionada"></div>
                            <hr>
                            <label>Outra marca:</label>
                            <input id="cadastrar-nova-marca" type="text" class="form-control">
                            <div id="produto_erro_marca"></div>
                            <button id="botao-cadastrar-nova-marca" type="button" class="btn btn-success mt-4">Adicionar Marca</button>
                        </div>
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-success form-control mb-3">Cadastrar Produto</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

<script src="/assets/js/produto_cadastrar.js"></script>