<?php
    include '../views/sections/header.html';
?>
<body class="fundo-cinza">
    <div class="container">
        <div class="row">
            <div class="col-12 mt-3 mb-3">
                <a href="/prod/buscar" class="btn btn-primary">Voltar</a>
            </div>
        </div>
        <h1>Atualizar Produto</h1>
        <div class="row">
            <div class="col-12">
                <form id="form-atualizar-produto" enctype="multipart/form-data">
                    <label>Nome <sup>*</sup></label>
                    <input id="produto_nome" type="text" class="form-control mb-3" name="produto_nome" value="<?= $produto['produto']; ?>">
                    <input id="id_produto" type="hidden" hidden="true" value="<?= $produto['id_produto']; ?>" name="id_produto">
                    <input id="status_produto_selecionado" hidden="true" value="<?= $produto['status']; ?>" name="status_produto_selecionado">
                    <div id="produto_erro_nome"></div>
                    <label>Descrição:</label>
                    <textarea id="produto_descricao" type="text" class="form-control mb-3" name="produto_descricao" rows="5"><?= $produto['descricao']; ?></textarea>
                    <div id="produto_erro_descricao"></div>
                    <div class="row">
                        <div class="col-md-2 col-sm-6 col-6">
                            <label>Cor:</label>
                            <input id="produto_cor" type="text" class="form-control mb-3" name="produto_cor" value="<?= $produto['cor']; ?>">
                        </div>
                        <div class="col-md-2 col-sm-6 col-6">
                            <label>Preço <sup>*</sup></label>
                            <input id="produto_valor_" type="text" class="form-control mb-3" name="produto_valor_" value="<?= number_format($produto['valor'],2,",","."); ?>">
                            <input id="produto_valor" type="text" class="form-control mb-3" name="produto_valor" hidden="true" value="<?= $produto['valor']; ?>">
                            <div id="produto_erro_valor"></div>
                        </div>
                        <div class="col-md-8">
                            <div class="row">
                                <div class="col-4">
                                    <label>Nº parcelas:</label>
                                    <input id="produto_nro_parcelas" type="text" class="form-control mb-3" name="produto_nro_parcelas" onkeypress='return event.charCode >= 48 && event.charCode <= 57' value="<?= $produto['nro_parcelas']; ?>">
                                    <div id="produto_erro_nro_parcelas"></div>
                                </div>
                                <div id="coluna-botao-calcular-parcelas" class="col-4">
                                    <button type="button" id="botao-calcular-parcelas" class="btn btn-primary mt-4">Calcular</button>
                                </div>
                                <div id="coluna-simbolo-igual" class="col-2">
                                    <h1 class="mt-3">=</h1>
                                </div>
                                <div class="col-2">
                                    <label>Valor Parcela:</label>
                                    <div id="valor_parcela"><b>R$ <?= number_format($produto['valor_parcela'],2,",","."); ?></b></div>
                                    <div id="valor_parcela_">
                                        <input id="produto_valor_parcela" type="hidden" hidden="true" name="produto_valor_parcela" value="<?= $produto['valor_parcela']; ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-3">
                            <label>Altura</label>
                            <input id="produto_altura" type="text" class="form-control mb-3" name="produto_altura" onkeyup="mascaraValorComVirgula('altura')" value="<?= str_replace('.', ',', ($produto['altura'] / 100)); ?>">
                            <input id="produto_altura_valor" type="hidden" hidden="true" class="form-control mb-3" name="produto_altura_valor" value="<?= $produto['altura'] / 100; ?>">
                            <div id="produto_erro_altura"></div>
                        </div>
                        <div class="col-3">
                            <label>Largura</label>
                            <input id="produto_largura" type="text" class="form-control mb-3" name="produto_largura" onkeyup="mascaraValorComVirgula('largura')" value="<?= str_replace('.', ',', ($produto['largura'] / 100)); ?>">
                            <input id="produto_largura_valor" type="hidden" hidden="true" class="form-control mb-3" name="produto_largura_valor" value="<?= $produto['largura'] / 100; ?>">
                            <div id="produto_erro_largura"></div>
                        </div>
                        <div class="col-3">
                            <label>Comprimento</label>
                            <input id="produto_comprimento" type="text" class="form-control mb-3" name="produto_comprimento" onkeyup="mascaraValorComVirgula('comprimento')" value="<?= str_replace('.', ',', ($produto['comprimento'] / 100)); ?>">
                            <input id="produto_comprimento_valor" type="hidden" hidden="true" class="form-control mb-3" name="produto_comprimento_valor" value="<?= $produto['comprimento'] / 100; ?>">
                            <div id="produto_erro_comprimento"></div>
                        </div>
                        <div class="col-3">
                            <label>Peso</label>
                            <input id="produto_peso" type="text" class="form-control mb-3" name="produto_peso" onkeyup="mascaraValorComVirgula('peso')" value="<?= str_replace('.', ',', $produto['peso']); ?>">
                            <input id="produto_peso_valor" type="hidden" class="form-control mb-3" name="produto_peso_valor" value="<?= $produto['peso']; ?>">
                            <div id="produto_erro_peso"></div>
                        </div> 
                    </div>
                    <hr>
                    <div class="row">
                        <div class="row mb-3">
                            <div class="col-4">
                                <label>Imagem Atual</label>
                                <div id="imagem_atual">
                                    <img src="/assets/img/<?= $produto['imagem']; ?>" height="85%" width="85%">
                                </div>
                                <div id="nova_imagem">
                                    <input id="imagem_" type="hidden" hidden="true" value="<?= $produto['imagem']; ?>">
                                </div>
                            </div>
                            <div class="col-8">
                                <label>Inserir Imagem</label>
                                <form id="alterar-imagem-produto" enctype="multipart/form-data">
                                    <input id="imagem" class="form-control mb-3" type="file" name="imagem_nova" accept="image/jpg, image/jpeg, image/gif">
                                    <button type="button" id="botao-alterar-imagem-produto" class="btn btn-primary">Alterar Imagem</button>
                                </form>
                                <div id="produto_erro_imagem"></div>
                            </div>
                        </div>
                        <hr>
                        <div class="col-md-6 col-sm-12">
                            <h5>Subcategorias Cadastradas <sup>*</sup></h5>
                            <div id="subcat-cadastradas"></div>
                            <div id="produto_erro_subcat"></div>
                            <select id="subcategoria-cadastrada-php" hidden="true">
                                <option value="<?= $produto['id_subcategoria']; ?>"><?= $produto['subcategoria']; ?></option>
                            </select>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <h5>Marcas Cadastradas <sup>*</sup></h5>
                            <div id="marcas-cadastradas"></div>
                            <div id="produto_erro_marca_selecionada"></div>
                            <select id="marca-cadastrada-php" hidden="true">
                                <option value="<?= $produto['id_marca']; ?>"><?= $produto['marca']; ?></option>
                            </select>
                            <hr>
                            <label>Outra marca:</label>
                            <input id="cadastrar-nova-marca" type="text" class="form-control">
                            <div id="produto_erro_marca"></div>
                            <button id="botao-cadastrar-nova-marca" type="button" class="btn btn-success mt-4">Adicionar Marca</button>
                        </div>
                    </div>
                    <hr>
                    <span class="h5">Controle de Exibição:</span>
                    <div class="form-check form-switch">
                        <input id="status-produto" type="checkbox" <?= $produto['status'] ? 'checked' : '' ?> class="form-check-input" name="status-produto" role="switch">
                        <div id="resposta-status">
                            <?php 
                                if($produto['status']) echo '<span class="h5 text-success">SIM, esse produto será exibido na loja virtual</span>';
                                else echo '<span class="h5 text-danger">NÃO, esse produto não será exibido na loja virtual</span>';
                            ?>
                        </div> 
                    </div>
                    <hr>
                    <button id="botao-editar-produto" type="button" class="btn btn-success form-control mb-3">Atualizar Produto</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

<script>

    $(document).ready(function() {
        let valor = 0
        
        $.ajax({
            type: "GET",
            url: "/subcategorias",
            dataType: "json",
            success: function (response) {
                if(response.length == 0) $('#subcat-cadastradas').html('<b class="text-danger">Sem Subcategorias Cadastradas</b>')
                else {
                    let html = '<select id="subcat-selecionada" class="form-control" name="subcat-selecionada"><option value="0">--- Selecione ---</option>'
                    response.forEach(element => {
                        html += `<option value="${element.id}" ${(element.id == <?= $produto['id_subcategoria']; ?>) ? 'selected' : '' }>${element.nome}</option>`
                    });
                    html += '</select>'
                    $('#subcat-cadastradas').html(html)
                }
            },
            error: function (error) {
                console.log(`erro: ${error}`)
            }
        });
        $.ajax({
            type: "GET",
            url: "/marcas",
            dataType: "json",
            success: function (response) {
                if(response.length == 0) $('#marcas-cadastradas').html('<b class="text-danger">Sem Marcas Cadastradas!</b>')
                else {
                    let html = '<select id="marca-selecionada" class="form-control" name="marca-selecionada"><option value="0">--- Selecione ---</option>'
                    response.forEach(element => {
                        html += `<option value="${element.id}" ${(element.id == <?= $produto['id_marca']; ?>) ? 'selected' : '' }>${element.nome}</option>`
                    });
                    html += '</select>'
                    $('#marcas-cadastradas').html(html)
                }
            },
            error: function (error) {
                console.log(`erro: ${error}`)
            }
        });

        $('#botao-calcular-parcelas').on('click', (e) => {
            if($('#produto_valor_').val() == '' || $('#produto_nro_parcelas').val() == '') {
                alert('Digite o preço do produto, e informe a quantidade de parcelas')
                $('#valor_parcela').html('<b>R$ 0,00</b>')
            }
            else {
                if($('#produto_nro_parcelas').val() == 0) {
                    $('#valor_parcela').html('<b>R$ 0,00</b>')
                }
                else {
                    let preco = $('#produto_valor_').val()
                    preco = preco.replace('.', '').replace(',', '.')
                    this.valor = parseFloat(preco)
                    $('#produto_valor').val(this.valor)
                    let nro_parcelas = ($('#produto_nro_parcelas').val())
                    let calculo = preco / nro_parcelas
                    let valorParcela = Math.floor(calculo * 100) / 100
                    let resultadoComVirgula = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(valorParcela)
                    valorParcela = valorParcela.toString()
                    valorParcela = valorParcela.replace(',', '.')
                    let html = `<b> ${resultadoComVirgula}</b>`
                    $('#valor_parcela').html(html)
                    $('#valor_parcela_').html(`<input id="produto_valor_parcela" type="hidden" hidden="true" name="produto_valor_parcela" value="${valorParcela}">`)
                }
            }
        })

        $('#botao-cadastrar-nova-marca').on('click', () => {
            let marca = $('#cadastrar-nova-marca')
            if(!marca.val()) {
                $('#cadastrar-nova-marca').css('border', '2px solid #FF0000')
                $('#produto_erro_marca').html('<span class="text-danger">Digite a Marca</span>')
                alert('Preencha a nova Marca!')
            }
            else {
                $.ajax({
                    type: "POST",
                    url: "/marca/cadastro",
                    data: {marca: marca.val()},
                    dataType: "json",
                    success: function (response) {
                        if(response == 1) {
                            alert('ATENÇÃO! Essa Marca já foi cadastrada!')
                        }
                        else if(response == 2) {
                            alert('Marca foi cadastrada com sucesso!!!')
                            $.ajax({
                                type: "GET",
                                url: "/marcas",
                                dataType: "json",
                                success: function (response) {
                                    let html = '<select id="marca-selecionada" class="form-control" name="marca-selecionada"><option value="0">--- Selecione ---</option>'
                                    response.forEach(element => {
                                        html += `<option value="${element.id}">${element.nome}</option>`
                                    });
                                    html += '</select>'
                                    $('#marcas-cadastradas').html(html)
                                    $('#cadastrar-nova-marca').css('border', '1px solid #D3D3D3')
                                    $('#produto_erro_marca').html('')
                                },
                                error: function (error) {
                                    console.log(`erro: ${error}`)
                                }
                            });
                        }
                    },
                    error: function (error) {
                        console.log(`erro: ${error}`)
                    }
                });
            }
        })

        $('#produto_valor_').on('keyup', (e) => { 
            var valorAlterado = e.target.value
            valorAlterado = valorAlterado.replace(/\D/g, "");
            valorAlterado = valorAlterado.replace(/(\d+)(\d{2})$/, "$1,$2");
            valorAlterado = valorAlterado.replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
            $('#produto_valor_').val(valorAlterado)
        });
        $('#botao-alterar-imagem-produto').on('click', (e) => {
            if($('#imagem').val() == '') alert('Selecione alguma imagem a ser inserida')
            else {
                let id_produto = $('#id_produto').val()
                let imagem_atual = $('#imagem_').val()
                let formData = new FormData()
                var imageFile = $('#imagem')[0].files[0]
                formData.append('imagem', imageFile)
                formData.append('imagem_atual', imagem_atual)
                formData.append('id_produto', id_produto)
                $.ajax({
                    type: "POST",
                    url: "/prod/img/alterar",
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        response = JSON.parse(response)
                        for(var indice in response) {
                            if(indice == 1) {
                                alert('Imagem foi alterada com sucesso!')
                                $('#imagem').val('')
                                $('#imagem_atual').html(`<img src="/assets/img/${response[indice]}" height="85%" width="85%">`)
                                $('#nova_imagem').html(`<input id="imagem_" type="hidden" hidden="true" value="${response[indice]}">`)
                            }
                            else if(indice == 5) {
                                alert('Erro ao gravar o nome da imagem na Loja Virtual')
                                $('#imagem').val('')
                            }
                            else if(indice == 4) {
                                alert('Não foi possível remover a imagem da pasta img')
                                $('#imagem').val('')
                            }
                            else if(indice == 3) {
                                alert('Arquivo de formato inválido! Selecione somente arquivos do tipo imagem')
                                $('#imagem').val('')
                            }
                            else if(indice == 2) {
                                alert('Não foi selecionada nenhuma imagem! Por favor, selecione uma imagem no campo imagem')
                                $('#imagem').val('')
                            }
                            else if(indice == 0) {
                                alert('Requisição HTTP inválida!')
                                $('#imagem').val('')
                            }
                        }
                    },
                    error: function (error) {
                        console.log(`erro: ${error}`)
                    }
                });
            }
        })

        $('#status-produto').on('click', () => {
            let status = $('#status-produto')
            let html = ''
            if(status[0].checked) {
                $('#resposta-status').html('<span class="h5 text-success">SIM, esse produto será exibido na loja virtual</span>')
                $('#status_produto_selecionado').val('1')
            }
            else {
                $('#resposta-status').html('<span class="h5 text-danger">NÃO, esse produto não será exibido na loja virtual</span>')
                $('#status_produto_selecionado').val('0')
            }
        })

        $('#botao-editar-produto').on('click', () => {
            let flagNome = true
            let flagPreco = true
            let flagValorParcela = true
            let flagNroParcelas = true
            let flagSubcategoria = true
            let flagMarca = true
            let flagImagem = true
            let flagAltura = true
            let flagLargura = true
            let flagComprimento = true
            let flagPeso = true
            if($('#produto_nome').val() === '') {
                $('#produto_nome').css('border', '2px solid #FF0000')
                $('#produto_erro_nome').html('<span class="text-danger">Preencha o Nome</span>')
                flagNome = false
            }
            else {
                $('#produto_nome').css('border', '1px solid #D3D3D3')
                $('#produto_erro_nome').html('')
                flagNome = true
            }
            if($('#produto_valor_').val() === '') {
                $('#produto_valor_').css('border', '1px solid #FF0000')
                $('#produto_erro_valor').html('<span class="text-danger">Preço ?</span>')
                flagPreco = false;
            }
            else {
                $('#produto_valor_').css('border', '1px solid #D3D3D3')
                $('#produto_erro_valor').html('')
                flagPreco = true;
            }
            if($('#produto_nro_parcelas').val() === '') {
                $('#produto_nro_parcelas').css('border', '1px solid #FF0000')
                $('#produto_erro_nro_parcelas').html('<span class="text-danger">Nº Parcelas ?</span>')
                flagNroParcelas = false
            }
            else {
                $('#produto_nro_parcelas').css('border', '1px solid #D3D3D3')
                $('#produto_erro_nro_parcelas').html('')
                flagNroParcelas = true
            }
            if($('#subcat-selecionada').val() == 0) {
                $('#subcat-selecionada').css('border', '3px solid #FF0000')
                $('#produto_erro_subcat').html('<span class="text-danger">Selecione a Subcategoria!</span>')
                flagSubcategoria = false
            }
            else {
                $('#subcat-selecionada').css('border', '1px solid #D3D3D3')
                $('#produto_erro_subcat').html('')
                flagSubcategoria = true
            }
            if($('#marca-selecionada').val() == 0) {
                $('#marca-selecionada').css('border', '3px solid #FF0000')
                $('#produto_erro_marca_selecionada').html('<span class="text-danger">Selecione a Marca!</span>')
                flagMarca = false
            }
            else {
                $('#marca-selecionada').css('border', '1px solid #D3D3D3')
                $('#produto_erro_marca_selecionada').html('')
                flagMarca = true
            }
            if($('#produto_altura').val() == '') {
                $('#produto_altura').css('border', '1px solid #FF0000')
                $('#produto_erro_altura').html('<span class="text-danger">Altura ?</span>')
                flagAltura = false
            }
            else {
                $('#produto_altura').css('border', '1px solid #D3D3D3')
                $('#produto_erro_altura').html('')
                flagAltura = true
            }
            if($('#produto_largura').val() == '') {
                $('#produto_largura').css('border', '1px solid #FF0000')
                $('#produto_erro_largura').html('<span class="text-danger">Largura ?</span>')
                flagAltura = false
            }
            else {
                $('#produto_largura').css('border', '1px solid #D3D3D3')
                $('#produto_erro_largura').html('')
                flagLargura = true
            }
            if($('#produto_comprimento').val() == '') {
                $('#produto_comprimento').css('border', '1px solid #FF0000')
                $('#produto_erro_comprimento').html('<span class="text-danger">Comprimento ?</span>')
                flagComprimento = false
            }
            else {
                $('#produto_comprimento').css('border', '1px solid #D3D3D3')
                $('#produto_erro_comprimento').html('')
                flagComprimento = true
            }
            if($('#produto_peso').val() == '') {
                $('#produto_peso').css('border', '1px solid #FF0000')
                $('#produto_erro_peso').html('<span class="text-danger">Peso ?</span>')
                flagPeso = false
            }
            else {
                $('#produto_peso').css('border', '1px solid #D3D3D3')
                $('#produto_erro_peso').html('')
                flagPeso = true
            }
            if(!flagNome || 
                !flagPreco || 
                !flagSubcategoria || 
                !flagMarca || 
                !flagAltura || 
                !flagLargura || 
                !flagComprimento || 
                !flagPeso) { alert('Atenção: Preencha os campos obrigatórios!')}
            else {
                let dados = $('#form-atualizar-produto').serialize()
                $.ajax({
                    type: "POST",
                    url: "/prod/update",
                    data: dados,
                    dataType: "json",
                    success: function (response) {
                        if(response) {
                            alert('Produto foi atualizado com sucesso!')
                            window.location.reload()
                        }
                        else alert('Não foi possível atualizar o Produto')
                    },
                    error: function (erro) { 
                        console.log(`erro: ${erro}`)
                     }
                });
            }
        })


    })

    function mascaraValorComVirgula(nome) {
        var valorAlterado = $(`#produto_${nome}`).val()
        valorAlterado = valorAlterado.replace(/\D/g, "");
        valorAlterado = valorAlterado.replace(/(\d+)(\d{2})$/, "$1,$2");
        var valorNumerico = valorAlterado
        valorNumerico = valorNumerico.replace(',', '.')
        $(`#produto_${nome}`).val(valorAlterado)
        $(`#produto_${nome}_valor`).val(valorNumerico)
    }

</script>