<?php
    $cssPedidos = $cssEndereco = $cssDadosPessoais = 'none';
    $uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
    switch($uri) {
        case '/cliente/painel/lista-enderecos':
            $cssEndereco = 'font-weight: bold; text-decoration: none';
            break;
        case '/cliente/painel/add-endereco':
            $cssEndereco = 'font-weight: bold; text-decoration: none';
            break;
        case '/cliente/painel/dados-pessoais':
            $cssDadosPessoais = 'font-weight: bold; text-decoration: none';
            break;
        case '/cliente/painel/editar-dados':
            $cssDadosPessoais = 'font-weight: bold; text-decoration: none';
            break;
        case '/cliente/painel/pedidos':
            $cssPedidos = 'font-weight: bold; text-decoration: none';
            break;
        case '/cliente/painel/pedido':
            $cssPedidos = 'font-weight: bold; text-decoration: none';
            break;
    }
?>
<div>
    <h3>Olá, <?= $_SESSION['nome']; ?></h3>
</div>
<div>
    <ul id="lista-sidebar">
        <li><a href="/cliente/painel/dados-pessoais" style="<?= $cssDadosPessoais; ?>" class="links-sidebar">Dados Pessoais</a><hr>
        <li><a href="/cliente/painel/lista-enderecos" style="<?= $cssEndereco; ?>" class="links-sidebar">Endereços</a></li><hr>
        <li><a href="/cliente/painel/pedidos" style="<?= $cssPedidos; ?>" class="links-sidebar">Pedidos</a></li>
    </ul>
</div>