<div>
    <h3>Olá, <?= $_SESSION['nome']; ?></h3>
</div>
<div>
    <ul class="links-sidebar-adm">
        <li class="mb-3"><a href="/catsub/add">Cadastrar Categoria / Subcategoria</a>
        <li><a href="/cat_sub/editar">Editar Categoria / Subcategoria</a><hr>
        <li class="mb-3"><a href="/prod/cadastro">Cadastrar Produto</a></li>
        <li><a href="/prod/buscar">Editar Produto</a></li><hr>
        <li><a href="/admin/editar-dados">Editar Dados</a><li>
    </ul>
</div>