<?php
    $opcao = 0;
    if(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) == '/cliente/painel' || parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) == '/login/validar') $opcao = 1;
    else if(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) != '/cliente/painel' || parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) != '/login/validar') $opcao = 2;
?>
<div class="col-10">
    <?php if($opcao == 1) { ?>
        <a id="botao-home" href="/" class="btn btn-primary">Loja</a>
        <h1 class="text-center">Meu Painel</h1>
    <?php } ?>
    <?php if($opcao == 2) { ?>
        <h1 class="text-center">Meu painel</h1>
    <?php } ?>
</div>
<div class="col-2">
    <a href="/logoff" class="btn btn-danger botao-sair">Sair</a>
</div>