<?php
    require_once '../helper/funcoes_adicionais.php';
    testarLogin();
?>
<?php include '../views/sections/header.html'; ?>
<body>
    <div class="container">
        <div class="row">
            <?php include_once '../views/sections/topo.phtml'; ?>
        </div>
        <div class="row">
            <div class="col-12">
                <a href="/cliente/painel/lista-enderecos" class="btn btn-primary botao-voltar-painel">Voltar</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <?php include_once '../views/sections/sidebar.phtml'; ?>
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-12">
                        <?php if(isset($_GET['erro']) == 1) { ?>
                            <div class="bg-danger-subtle text-danger-emphasis p-3 mb-3 text-center mensagem-erro-preencher-dados">Por Favor, preencha todos os campos abaixo corretamente!</div>
                        <?php } ?>
                        <?php if(isset($_GET['msg']) && $_GET['msg'] == 0) { ?>
                            <div class="bg-danger-subtle text-danger-emphasis p-3 mb-3 text-center">
                                Esse Endereço já existe!
                            </div>
                        <?php } ?>
                        <?php if(isset($_GET['msg']) && $_GET['msg'] == 1) { ?>
                            <div class="bg-success-subtle text-success-emphasis p-3 mb-3 text-center">
                                Cadastro realizado com sucesso
                            </div>
                        <?php } ?>
                        <form method="POST" action="/cliente/painel/criar-endereco" novalidate>
                            <h4>Adicione um Endereço de Entrega</h4>
                            <div class="row">
                                <div class="col-sm-3">
                                    <label>Nº</label>
                                    <input class="form-control mb-4 campo_form_cliente" type="text" name="numero">
                                </div>
                                <div class="col-sm-3">
                                    <label>Complemento<sup>opcional</sup></label>
                                    <input class="form-control" type="text" name="complemento">
                                </div>
                                <div class="col-sm-6">
                                    <label>CEP</label>
                                    <input id="cep" class="form-control mb-4 campo_form_cliente" type="text" name="cep" onkeypress='return event.charCode >= 48 && event.charCode <= 57' maxlength="8">
                                    <div id="msg-erro"></div>
                                </div>
                            </div>
                            <label>Rua/Avenida</label>
                            <input id="rua" class="form-control mb-4 bg-light" type="text" name="logradouro" readonly>
                            <label>Bairro</label>
                            <input id="bairro" class="form-control mb-4 bg-light" type="text" name="bairro" readonly>
                            <label>Cidade</label>
                            <input id="cidade" class="form-control mb-4 bg-light" type="text" name="cidade" readonly>
                            <label>UF</label>
                            <input id="uf" class="form-control mb-4 bg-light" type="text" name="uf" readonly>
                            <input class="form-control btn btn-success" type="submit" id="botao-enviar-login" value="Cadastrar Endereço">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>