<?php
    include '../views/sections/header.html';
    require_once '../helper/funcoes_adicionais.php';
?>
<body>
    <div class="container">
        <div class="row">
            <div class="col-10">
                <a href="/cliente/painel" class="btn btn-primary">Voltar</a>
            </div>
            <div class="col-2">
                <div class="float-end">
                    <a href="/logoff" class="btn btn-danger">Sair</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <div class="text-center"><h1>Detalhes do Pedido</h1></div>
                <div id="pedido-adm" class="mb-3">
                    <div class="row">
                        <div class="col-12">
                            <span>Pedido: </span><span><?= $resultado['pedido'][0]['id_pedido']; ?></span>
                            <span>Data: </span><span><?php 
                                                        $data = $resultado['pedido'][0]['data_compra'];
                                                        $data = explode('-', $data);
                                                        echo $data[2].'/'.$data[1].'/'.$data[0]; 
                                                    ?></span>
                            <span>às <?= $resultado['pedido'][0]['hora_compra']; ?> h</span>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-12 col-md-6">
                            Cliente: <?= $resultado['pedido'][0]['nome']; ?>
                        </div>
                        <div class="col-12 col-md-6">
                            e-mail: <?= $resultado['pedido'][0]['email']; ?>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-3 borda-dir">
                            Status do Pedido: <b><?= $resultado['pedido'][0]['status_entrega']; ?></b>
                        </div>
                        <div class="col-3 borda-dir">
                            Entrega em: <b><?php 
                                                $data = $resultado['pedido'][0]['data_entrega'];
                                                $data = explode('-', $data);
                                                echo $data[2].'/'.$data[1].'/'.$data[0]; 
                                            ?></b>
                        </div>
                        <div class="col-6">
                            Endereço de Entrega:<br>
                            <b><?= $resultado['pedido'][0]['logradouro']; ?></b><br>
                            <b>Nº: <?= $resultado['pedido'][0]['numero']; ?></b><br>
                            <?php if(!(empty($resultado['pedido'][0]['complemento']))) { ?>
                                <b>Complemento: <?= $resultado['pedido'][0]['complemento']; ?></b><br>
                            <?php } ?>
                            <b><?= $resultado['pedido'][0]['bairro']; ?> - <?= $resultado['pedido'][0]['cidade']; ?> - <?= $resultado['pedido'][0]['uf']; ?></b><br>
                            <b><?= aplicarMascara($resultado['pedido'][0]['cep'], '#####-###'); ?></b>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div>Produto(s)</div>
                        <?php for($i = 0; $i < count($resultado['item']); $i++) { ?>
                            <div class="col-2">
                                <div>
                                    <img src="/assets/img/<?= $resultado['item'][$i]['imagem_path']; ?>" width="60">
                                </div>
                            </div>
                            <div class="col-10">
                                Produto: <?= $resultado['item'][$i]['Produto']; ?><br>
                                Marca: <?= $resultado['item'][$i]['Marca']; ?><br>
                                Quantidade: <?= $resultado['item'][$i]['Quant']; ?><br>
                                Preço: <?= number_format($resultado['item'][$i]['preco_unit'],2,",","."); ?><br>
                                Total: R$ <?= number_format($resultado['item'][$i]['Total'],2,",","."); ?>
                            </div>
                            <hr>
                        <?php } ?>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <div>Pagamento</div>
                            Forma: <?= $resultado['pgto']['tipo']; ?><br>
                            <?php if($resultado['pedido'][0]['id_modalidade'] == 2) { ?>
                                Data Vencimento: <?php 
                                                    $data = $resultado['pgto']['data_vencimento'];
                                                    $data = explode('-', $data);
                                                    echo $data[2].'/'.$data[1].'/'.$data[0];
                                                ?><br>
                                Status de Pagamento: <?= $resultado['pgto']['status']; ?>
                                <br><br>
                            <?php } ?>
                            <?php if($resultado['pedido'][0]['id_modalidade'] == 1) { ?>
                                <?= $resultado['pgto']['nro_parcelas']; ?> X R$ <?= number_format($resultado['pgto']['valor_parcela'],2,",","."); ?><br>
                                Status de Pagamento: <?= $resultado['pgto']['status']; ?><br><br>
                            <?php } ?>
                            Tipo de Entrega: <?= $resultado['pedido'][0]['forma_envio']; ?><br>
                            Empresa: <?= $resultado['pedido'][0]['transportadora']; ?>
                        </div>
                        <div class="col-3">
                            <?php if(isset($resultado['pgto']['bandeira'])) { ?>
                                Compra autorizada cartão do Cliente<br>
                                <div class="text-center">
                                    <i id="bandeira-simbolo" class="fa-brands fa-cc-<?= $resultado['pgto']['bandeira']; ?>"></i>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="col-12 pb-3">
                            <hr>
                            <div>Resumo do Pedido</div>
                            SUBTOTAL: <div class="float-end">R$ <?= number_format($resultado['pedido'][0]['valor'],2,",","."); ?></div><hr>
                            FRETE: <div class="float-end">R$ <?= number_format($resultado['pedido'][0]['preco_frete'],2,",","."); ?></div><hr>
                            TOTAL: <div class="float-end">R$ <?= number_format($resultado['pedido'][0]['valor_com_frete'],2,",","."); ?></div>
                        </div>
                    </div>
                    <hr>
                    <div class="row mb-3">
                        <div class="col-12 col-md-4 col-lg-5">
                            Alterar Status de Entrega
                        </div>
                        <div class="col-8 col-md-5 col-lg-5">
                            <form id="formulario-alterar-status-entrega">
                                <select class="form-control" name="alterar-status-entrega">
                                    <option value="1" <?= $resultado['pedido'][0]['status_entrega'] == 'PENDENTE' ? 'selected' : ''; ?>>PENDENTE</option>
                                    <option value="2" <?= $resultado['pedido'][0]['status_entrega'] == 'EM TRÂNSITO' ? 'selected' : ''; ?>>EM TRÂNSITO</option>
                                    <option value="3" <?= $resultado['pedido'][0]['status_entrega'] == 'ENVIADO' ? 'selected' : ''; ?>>ENVIADO</option>
                                    <option value="4" <?= $resultado['pedido'][0]['status_entrega'] == 'ENTREGUE' ? 'selected' : ''; ?>>ENTREGUE</option>
                                    <option value="0" <?= $resultado['pedido'][0]['status_entrega'] == 'CANCELADO' ? 'selected' : ''; ?>>CANCELADO</option>
                                </select>
                                <input type="hidden" hidden="true" value="<?= $resultado['pedido'][0]['id_pedido']; ?>" name="id_pedido">
                        </div>
                        <div class="col-4 col-md-3 col-lg-2">
                            <button type="button" id="botao-alterar-status-entrega" class="btn btn-success">Alterar</button>
                        </div>
                        </form>
                    </div>
                    <div class="row mb-3">
                        <div class="col-lg-5 col-md-4 col-sm-5">
                            Status de Pagamento:
                        </div>
                        <div id="statusPgto" class="col-8 col-lg-6 col-md-6 col-sm-6 w-25">
                            <input type="text" class="form-control" value="<?= $resultado['pgto']['status']; ?>" disabled>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="/assets/js/pedido_adm.js"></script>